edition: 1.0.0
name: container-build-demo
access: "quanxi"
vars:
  region: cn-shenzhen
services:
  customContainer-build-demo:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: fc-build-demo
        internetAccess: true
      function:
        name: event-container-function
        description: event function powered by flask
        handler: not-used
        timeout: 60
        caPort: 8080
        memorySize: 512
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/fc-demo2/fc-flask:v0.1
        codeUri: ./
# 函数计算FC组件文档参考地址：https://github.com/devsapp/fc
