name: Serverless Devs Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-ci:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: check install docker
        run: |
          docker -v
      - name: test docker run
        run: |
          docker run busybox /bin/sh -c "ls -lh"
      - name: npm install s
        run: |
          npm install -g @serverless-devs/s
      - name: s config
        run: |
          s config add --AccessKeyID ${{secrets.ACCESSKEYID}} --AccessKeySecret ${{secrets.ACCESSKEYSECRET}} -a quanxi -f
      - name: test python
        run: |
          bash test-python.sh
      - name: test nodejs
        run: |
          bash test-node.sh
      - name: test php
        run: |
          bash test-php.sh
      - name: test custom 
        run: |
          bash test-cr.sh
      - name: test custom container
        run: |
          bash test-ccr.sh
      - name: test java
        run: |
          bash test-java.sh